sudo: false

language: python

cache:
    apt: true

addons:
    apt:
        packages:
            - curl
            - libfcgi0ldbl

services:
  - docker

before_install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" $DOCKER_REGISTER;
  - docker build 
        --no-cache 
        -t 03192859189254/magento-cli-alpine:latest-dev
        --build-arg BUILD_COMMIT=`git rev-parse --short HEAD` 
        --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` .

script:
# Starting magento-cli container
 - TEST_CONTAINER_MAGENTO_CLI_ID=$( docker run -d --name=magento-cli-alpine 03192859189254/magento-cli-alpine:latest-dev )
 - TEST_CONTAINER_MAGENTO_CLI_STATUS=$(sleep 5 && docker inspect -f '{{.State.Running}}' $TEST_CONTAINER_MAGENTO_CLI_ID)

# Testing magento-cli container
 - if [ ! "$TEST_CONTAINER_MAGENTO_CLI_STATUS" = "true" ]; then
        echo "Magento-cli container failed, print logs and exiting\n";
        docker logs $TEST_CONTAINER_MAGENTO_CLI_ID;
    fi
# Echo success
 - if [ "$TEST_CONTAINER_MAGENTO_CLI_STATUS" = "true" ]; then
        echo "### Test Succeeded\n";
    fi


after_success:
  - if [ "$DOCKER_USERNAME" ]; then
        docker tag 03192859189254/magento-cli-alpine:latest-dev ${DOCKER_REGISTER}/${DOCKER_USERNAME}/magento-cli-alpine:latest-dev;
        docker push ${DOCKER_REGISTER}/${DOCKER_USERNAME}/magento-cli-alpine:latest-dev;
    fi